# Generated by Django 5.1.4 on 2024-12-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('depart_date', models.DateField()),
                ('return_date', models.DateField()),
                ('duration', models.CharField(max_length=50)),
            ],
        ),
    ]
