# Generated by Django 5.1.3 on 2025-01-16 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
