# Generated by Django 5.2.1 on 2025-06-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.ImageField(default='patient/images/default.png', upload_to='patient/images/'),
        ),
    ]
