# Generated by Django 5.2.1 on 2025-06-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_alter_patient_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(default='Chittagong', max_length=30),
        ),
    ]
