# Generated by Django 5.2.1 on 2025-06-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
