# Generated by Django 5.2.1 on 2025-06-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='phone',
        ),
        migrations.AddField(
            model_name='contactus',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=20),
        ),
    ]
