# Generated by Django 5.2.1 on 2025-06-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_remove_contactus_phone_contactus_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
