# Generated by Django 5.2.1 on 2025-06-27 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebooking',
            name='name',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='phone',
        ),
    ]
