# Generated by Django 5.2.1 on 2025-06-28 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_patient_address'),
        ('service', '0002_remove_servicebooking_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebooking',
            name='user',
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
        ),
    ]
